### ISSUE TITLE
Trouble installing ipyrad

### ISSUE THREAD

**Issue by YaraAlshw** [YaraAlshw/finalproject#2]
I followed the steps in this tutorial: [https://radcamp.github.io/Yale2019/ipyrad_Install_Quickstart.html](url) to install ipyrad on Grace. Everything seemed to work fine, as I continued with the tutorial part 1 and tried the "help" command, I got the following errors:

(ipyrad)[eeb354_yaa23@ondemand1 project]$ ipyrad --help

Traceback (most recent call last):
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/bin/ipyrad", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3267, in <module>
    @_call_aside
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in _call_aside
    f(*args, **kwargs)
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3280, in _initialize_master_wo
rking_set
    working_set = WorkingSet._build_master()
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ipyrad==0.7.17' distribution was not found and is required by the application
(ipyrad)[eeb354_yaa23@ondemand1 project]$ ipyrad --help
Traceback (most recent call last):
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/bin/ipyrad", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3267, in <module>
    @_call_aside
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in _call_aside
    f(*args, **kwargs)
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3280, in _initialize_master_wo
rking_set
    working_set = WorkingSet._build_master()
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ipyrad==0.7.17' distribution was not found and is required by the application

**Comment by YaraAlshw** [comment]
Trying this again gave this error:

"(ipyrad)[eeb354_yaa23@ondemand1 project]$ ipyrad --help 
Traceback (most recent call last):
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/bin/ipyrad", line 33, in <module>
    sys.exit(load_entry_point('ipyrad==0.1.32', 'console_scripts', 'ipyrad')())
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/bin/ipyrad", line 25, in importlib_load_e
ntry_point
    return next(matches).load()
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/importlib_met
adata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/importlib/__init__.py", lin
e 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32
-py3.6.egg/ipyrad/__init__.py", line 4, in <module>
    from . import load
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32
-py3.6.egg/ipyrad/load/__init__.py", line 16, in <module>
    from .load import load_assembly
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32
-py3.6.egg/ipyrad/load/load.py", line 13, in <module>
    from ipyrad.core.assembly import Assembly
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32
-py3.6.egg/ipyrad/core/assembly.py", line 27, in <module>
    from ipyrad.assemble.util import *
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32
-py3.6.egg/ipyrad/assemble/__init__.py", line 2, in <module>
    from . import demultiplex
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/assemble/demultiplex.py", line 14, in <module>
    import cPickle as pickle
ModuleNotFoundError: No module named 'cPickle'
(ipyrad)[eeb354_yaa23@ondemand1 project]$ --help
bash: --help: command not found...
(ipyrad)[eeb354_yaa23@ondemand1 project]$ conda --version
conda 4.8.3
(ipyrad)[eeb354_yaa23@ondemand1 project]$ ipyrad --version
Traceback (most recent call last):
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/bin/ipyrad", line 33, in <module>
    sys.exit(load_entry_point('ipyrad==0.1.32', 'console_scripts', 'ipyrad')())
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/bin/ipyrad", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/__init__.py", line 4, in <module>
    from . import load
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/load/__init__.py", line 16, in <module>
    from .load import load_assembly
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/load/load.py", line 13, in <module>
    from ipyrad.core.assembly import Assembly
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/core/assembly.py", line 27, in <module>
    from ipyrad.assemble.util import *
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/assemble/__init__.py", line 2, in <module>
    from . import demultiplex
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/assemble/demultiplex.py", line 14, in <module>
    import cPickle as pickle
ModuleNotFoundError: No module named 'cPickle'
(ipyrad)[eeb354_yaa23@ondemand1 project]$ source activate ipyrad
(ipyrad)[eeb354_yaa23@ondemand1 project]$ ipyrad --help 
Traceback (most recent call last):
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/bin/ipyrad", line 33, in <module>
    sys.exit(load_entry_point('ipyrad==0.1.32', 'console_scripts', 'ipyrad')())
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/bin/ipyrad", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/__init__.py", line 4, in <module>
    from . import load
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/load/__init__.py", line 16, in <module>
    from .load import load_assembly
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/load/load.py", line 13, in <module>
    from ipyrad.core.assembly import Assembly
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/core/assembly.py", line 27, in <module>
    from ipyrad.assemble.util import *
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/assemble/__init__.py", line 2, in <module>
    from . import demultiplex
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/assemble/demultiplex.py", line 14, in <module>
    import cPickle as pickle
ModuleNotFoundError: No module named 'cPickle'
(ipyrad)[eeb354_yaa23@ondemand1 project]$ ipyrad -n test1
Traceback (most recent call last):
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/bin/ipyrad", line 33, in <module>
    sys.exit(load_entry_point('ipyrad==0.1.32', 'console_scripts', 'ipyrad')())
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/bin/ipyrad", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/__init__.py", line 4, in <module>
    from . import load
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/load/__init__.py", line 16, in <module>
    from .load import load_assembly
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/load/load.py", line 13, in <module>
    from ipyrad.core.assembly import Assembly
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/core/assembly.py", line 27, in <module>
    from ipyrad.assemble.util import *
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/assemble/__init__.py", line 2, in <module>
    from . import demultiplex
  File "/gpfs/loomis/project/eeb354/eeb354_yaa23/conda_envs/ipyrad/lib/python3.6/site-packages/ipyrad-0.1.32-py3.6.egg/ipyrad/assemble/demultiplex.py", line 14, in <module>
    import cPickle as pickle
ModuleNotFoundError: No module named 'cPickle'"

**Comment by YaraAlshw** [comment]
Fixed the issue with these commands, thanks to Lauren and Ben!

**Comment by caseywdunn** [comment]
Very glad to hear that this works.
